[package]
name = "tuturu"
version = "0.1.0"
authors = ["Philippe Guilbault <pguilbault@proton.me>"]
edition = "2018"

[dependencies]
kurisu = {path = "../"}

[[bin]]
name = "cabi"
path = "src/bin/cabi.rs"
